services:
  humanode:
    image: ghcr.io/piconbello/humanode-docker:${HMND_IMAGE_TAG:-latest}
    container_name: humanode-validator
    restart: always
    env_file: .env
    volumes:
      - ./data:/data
    ports:
      - "30333:30333/tcp"
