#!/command/with-contenv sh
set -eu

NODE_NAME="${NODE_NAME:-humanode-validator}"
SYNC_MODE="${SYNC_MODE:-full}"

exec 2>&1
exec s6-setuidgid hmnd \
    humanode-peer \
        --validator \
        --chain /etc/humanode/chainspec.json \
        --base-path /data \
        --name "${NODE_NAME}" \
        --rpc-port 9944 \
        --rpc-cors all \
        --sync "${SYNC_MODE}" \
        --port 30333
